const dropdownCities = {
  // 北部 7 個縣市
  north: [
    {
      countryId: "63",
      countryName: "台北市",
      districts: [
        { districtId: "100", districtName: "中正區" },
        { districtId: "103", districtName: "大同區" },
        { districtId: "104", districtName: "中山區" },
        { districtId: "105", districtName: "松山區" },
        { districtId: "106", districtName: "大安區" },
        { districtId: "108", districtName: "萬華區" },
        { districtId: "110", districtName: "信義區" },
        { districtId: "111", districtName: "士林區" },
        { districtId: "112", districtName: "北投區" },
        { districtId: "114", districtName: "內湖區" },
        { districtId: "115", districtName: "南港區" },
        { districtId: "116", districtName: "文山區" },
      ],
    },
    {
      countryId: "65",
      countryName: "新北市",
      districts: [
        { districtId: "207", districtName: "萬里區" },
        { districtId: "208", districtName: "金山區" },
        { districtId: "220", districtName: "板橋區" },
        { districtId: "221", districtName: "汐止區" },
        { districtId: "222", districtName: "深坑區" },
        { districtId: "223", districtName: "石碇區" },
        { districtId: "224", districtName: "瑞芳區" },
        { districtId: "226", districtName: "平溪區" },
        { districtId: "227", districtName: "雙溪區" },
        { districtId: "228", districtName: "貢寮區" },
        { districtId: "231", districtName: "新店區" },
        { districtId: "232", districtName: "坪林區" },
        { districtId: "233", districtName: "烏來區" },
        { districtId: "234", districtName: "永和區" },
        { districtId: "235", districtName: "中和區" },
        { districtId: "236", districtName: "土城區" },
        { districtId: "237", districtName: "三峽區" },
        { districtId: "238", districtName: "樹林區" },
        { districtId: "239", districtName: "鶯歌區" },
        { districtId: "241", districtName: "三重區" },
        { districtId: "242", districtName: "新莊區" },
        { districtId: "243", districtName: "泰山區" },
        { districtId: "244", districtName: "林口區" },
        { districtId: "247", districtName: "蘆洲區" },
        { districtId: "248", districtName: "五股區" },
        { districtId: "249", districtName: "八里區" },
        { districtId: "251", districtName: "淡水區" },
        { districtId: "252", districtName: "三芝區" },
        { districtId: "253", districtName: "石門區" },
      ],
    },
    {
      countryId: "68",
      countryName: "桃園市",
      districts: [
        { districtId: "320", districtName: "中壢區" },
        { districtId: "324", districtName: "平鎮區" },
        { districtId: "325", districtName: "龍潭區" },
        { districtId: "326", districtName: "楊梅區" },
        { districtId: "327", districtName: "新屋區" },
        { districtId: "328", districtName: "觀音區" },
        { districtId: "330", districtName: "桃園區" },
        { districtId: "333", districtName: "龜山區" },
        { districtId: "334", districtName: "八德區" },
        { districtId: "335", districtName: "大溪區" },
        { districtId: "336", districtName: "復興區" },
        { districtId: "337", districtName: "大園區" },
        { districtId: "338", districtName: "蘆竹區" },
      ],
    },
    {
      countryId: "10018",
      countryName: "新竹市",
      districts: [
        { districtId: "30001", districtName: "東區" },
        { districtId: "30002", districtName: "北區" },
        { districtId: "30003", districtName: "香山區" },
      ],
    },
    {
      countryId: "10004",
      countryName: "新竹縣",
      districts: [
        { districtId: "302", districtName: "竹北市" },
        { districtId: "303", districtName: "湖口鄉" },
        { districtId: "304", districtName: "新豐鄉" },
        { districtId: "305", districtName: "新埔鎮" },
        { districtId: "306", districtName: "關西鎮" },
        { districtId: "307", districtName: "芎林鄉" },
        { districtId: "308", districtName: "寶山鄉" },
        { districtId: "310", districtName: "竹東鎮" },
        { districtId: "311", districtName: "五峰鄉" },
        { districtId: "312", districtName: "橫山鄉" },
        { districtId: "313", districtName: "尖石鄉" },
        { districtId: "314", districtName: "北埔鄉" },
        { districtId: "315", districtName: "峨眉鄉" },
      ],
    },
    {
      countryId: "10002",
      countryName: "宜蘭縣",
      districts: [
        { districtId: "260", districtName: "宜蘭市" },
        { districtId: "261", districtName: "頭城鎮" },
        { districtId: "262", districtName: "礁溪鄉" },
        { districtId: "263", districtName: "壯圍鄉" },
        { districtId: "264", districtName: "員山鄉" },
        { districtId: "265", districtName: "羅東鎮" },
        { districtId: "266", districtName: "三星鄉" },
        { districtId: "267", districtName: "大同鄉" },
        { districtId: "268", districtName: "五結鄉" },
        { districtId: "269", districtName: "冬山鄉" },
        { districtId: "270", districtName: "蘇澳鎮" },
        { districtId: "272", districtName: "南澳鄉" },
      ],
    },
    {
      countryId: "10017",
      countryName: "基隆市",
      districts: [
        { districtId: "200", districtName: "仁愛區" },
        { districtId: "201", districtName: "信義區" },
        { districtId: "202", districtName: "中正區" },
        { districtId: "203", districtName: "中山區" },
        { districtId: "204", districtName: "安樂區" },
        { districtId: "205", districtName: "暖暖區" },
        { districtId: "206", districtName: "七堵區" },
      ],
    },
  ],
  // 中部 5 個縣市
  central: [
    {
      countryId: "10005",
      countryName: "苗栗縣",
      districts: [
        { districtId: "350", districtName: "竹南鎮" },
        { districtId: "351", districtName: "頭份市" },
        { districtId: "352", districtName: "三灣鄉" },
        { districtId: "353", districtName: "南庄鄉" },
        { districtId: "354", districtName: "獅潭鄉" },
        { districtId: "356", districtName: "後龍鎮" },
        { districtId: "357", districtName: "通霄鎮" },
        { districtId: "358", districtName: "苑裡鎮" },
        { districtId: "360", districtName: "苗栗市" },
        { districtId: "361", districtName: "造橋鄉" },
        { districtId: "362", districtName: "頭屋鄉" },
        { districtId: "363", districtName: "公館鄉" },
        { districtId: "364", districtName: "大湖鄉" },
        { districtId: "365", districtName: "泰安鄉" },
        { districtId: "366", districtName: "銅鑼鄉" },
        { districtId: "367", districtName: "三義鄉" },
        { districtId: "368", districtName: "西湖鄉" },
        { districtId: "369", districtName: "卓蘭鎮" },
      ],
    },
    {
      countryId: "66",
      countryName: "台中市",
      districts: [
        { districtId: "400", districtName: "中區" },
        { districtId: "401", districtName: "東區" },
        { districtId: "402", districtName: "南區" },
        { districtId: "403", districtName: "西區" },
        { districtId: "404", districtName: "北區" },
        { districtId: "406", districtName: "北屯區" },
        { districtId: "407", districtName: "西屯區" },
        { districtId: "408", districtName: "南屯區" },
        { districtId: "411", districtName: "太平區" },
        { districtId: "412", districtName: "大里區" },
        { districtId: "413", districtName: "霧峰區" },
        { districtId: "414", districtName: "烏日區" },
        { districtId: "420", districtName: "豐原區" },
        { districtId: "421", districtName: "后里區" },
        { districtId: "422", districtName: "石岡區" },
        { districtId: "423", districtName: "東勢區" },
        { districtId: "424", districtName: "和平區" },
        { districtId: "426", districtName: "新社區" },
        { districtId: "427", districtName: "潭子區" },
        { districtId: "428", districtName: "大雅區" },
        { districtId: "429", districtName: "神岡區" },
        { districtId: "432", districtName: "大肚區" },
        { districtId: "433", districtName: "沙鹿區" },
        { districtId: "434", districtName: "龍井區" },
        { districtId: "435", districtName: "梧棲區" },
        { districtId: "436", districtName: "清水區" },
        { districtId: "437", districtName: "大甲區" },
        { districtId: "438", districtName: "外埔區" },
        { districtId: "439", districtName: "大安區" },
      ],
    },
    {
      countryId: "10007",
      countryName: "彰化縣",
      districts: [
        { districtId: "500", districtName: "彰化市" },
        { districtId: "502", districtName: "芬園鄉" },
        { districtId: "503", districtName: "花壇鄉" },
        { districtId: "504", districtName: "秀水鄉" },
        { districtId: "505", districtName: "鹿港鎮" },
        { districtId: "506", districtName: "福興鄉" },
        { districtId: "507", districtName: "線西鄉" },
        { districtId: "508", districtName: "和美鎮" },
        { districtId: "509", districtName: "伸港鄉" },
        { districtId: "510", districtName: "員林市" },
        { districtId: "511", districtName: "社頭鄉" },
        { districtId: "512", districtName: "永靖鄉" },
        { districtId: "513", districtName: "埔心鄉" },
        { districtId: "514", districtName: "溪湖鎮" },
        { districtId: "515", districtName: "大村鄉" },
        { districtId: "516", districtName: "埔鹽鄉" },
        { districtId: "520", districtName: "田中鎮" },
        { districtId: "521", districtName: "北斗鎮" },
        { districtId: "522", districtName: "田尾鄉" },
        { districtId: "523", districtName: "埤頭鄉" },
        { districtId: "524", districtName: "溪州鄉" },
        { districtId: "525", districtName: "竹塘鄉" },
        { districtId: "526", districtName: "二林鎮" },
        { districtId: "527", districtName: "大城鄉" },
        { districtId: "528", districtName: "芳苑鄉" },
        { districtId: "530", districtName: "二水鄉" },
      ],
    },
    {
      countryId: "10009",
      countryName: "雲林縣",
      districts: [
        { districtId: "630", districtName: "斗南鎮" },
        { districtId: "631", districtName: "大埤鄉" },
        { districtId: "632", districtName: "虎尾鎮" },
        { districtId: "633", districtName: "土庫鎮" },
        { districtId: "634", districtName: "褒忠鄉" },
        { districtId: "635", districtName: "東勢鄉" },
        { districtId: "636", districtName: "臺西鄉" },
        { districtId: "637", districtName: "崙背鄉" },
        { districtId: "638", districtName: "麥寮鄉" },
        { districtId: "640", districtName: "斗六市" },
        { districtId: "643", districtName: "林內鄉" },
        { districtId: "646", districtName: "古坑鄉" },
        { districtId: "647", districtName: "莿桐鄉" },
        { districtId: "648", districtName: "西螺鎮" },
        { districtId: "649", districtName: "二崙鄉" },
        { districtId: "651", districtName: "北港鎮" },
        { districtId: "652", districtName: "水林鄉" },
        { districtId: "653", districtName: "口湖鄉" },
        { districtId: "654", districtName: "四湖鄉" },
        { districtId: "655", districtName: "元長鄉" },
      ],
    },

    {
      countryId: "10008",
      countryName: "南投縣",
      districts: [
        { districtId: "540", districtName: "南投市" },
        { districtId: "541", districtName: "中寮鄉" },
        { districtId: "542", districtName: "草屯鎮" },
        { districtId: "544", districtName: "國姓鄉" },
        { districtId: "545", districtName: "埔里鎮" },
        { districtId: "546", districtName: "仁愛鄉" },
        { districtId: "551", districtName: "名間鄉" },
        { districtId: "552", districtName: "集集鎮" },
        { districtId: "553", districtName: "水里鄉" },
        { districtId: "555", districtName: "魚池鄉" },
        { districtId: "556", districtName: "信義鄉" },
        { districtId: "557", districtName: "竹山鎮" },
        { districtId: "558", districtName: "鹿谷鄉" },
      ],
    },
  ],
  // 南部 5 個縣市
  south: [
    {
      countryId: "10010",
      countryName: "嘉義縣",
      districts: [
        { districtId: "602", districtName: "番路鄉" },
        { districtId: "603", districtName: "梅山鄉" },
        { districtId: "604", districtName: "竹崎鄉" },
        { districtId: "606", districtName: "中埔鄉" },
        { districtId: "607", districtName: "大埔鄉" },
        { districtId: "608", districtName: "水上鄉" },
        { districtId: "611", districtName: "鹿草鄉" },
        { districtId: "612", districtName: "太保市" },
        { districtId: "613", districtName: "朴子市" },
        { districtId: "614", districtName: "東石鄉" },
        { districtId: "615", districtName: "六腳鄉" },
        { districtId: "616", districtName: "新港鄉" },
        { districtId: "621", districtName: "民雄鄉" },
        { districtId: "622", districtName: "大林鎮" },
        { districtId: "623", districtName: "溪口鄉" },
        { districtId: "624", districtName: "義竹鄉" },
        { districtId: "625", districtName: "布袋鎮" },
        { districtId: "605", districtName: "阿里山鄉" },
      ],
    },
    {
      countryId: "10020",
      countryName: "嘉義市",
      districts: [
        { districtId: "60001", districtName: "東區" },
        { districtId: "60002", districtName: "西區" },
      ],
    },

    {
      countryId: "67",
      countryName: "台南市",
      districts: [
        { districtId: "700", districtName: "中西區" },
        { districtId: "701", districtName: "東區" },
        { districtId: "702", districtName: "南區" },
        { districtId: "704", districtName: "北區" },
        { districtId: "708", districtName: "安平區" },
        { districtId: "709", districtName: "安南區" },
        { districtId: "710", districtName: "永康區" },
        { districtId: "711", districtName: "歸仁區" },
        { districtId: "712", districtName: "新化區" },
        { districtId: "713", districtName: "左鎮區" },
        { districtId: "714", districtName: "玉井區" },
        { districtId: "715", districtName: "楠西區" },
        { districtId: "716", districtName: "南化區" },
        { districtId: "717", districtName: "仁德區" },
        { districtId: "718", districtName: "關廟區" },
        { districtId: "719", districtName: "龍崎區" },
        { districtId: "720", districtName: "官田區" },
        { districtId: "721", districtName: "麻豆區" },
        { districtId: "722", districtName: "佳里區" },
        { districtId: "723", districtName: "西港區" },
        { districtId: "724", districtName: "七股區" },
        { districtId: "725", districtName: "將軍區" },
        { districtId: "726", districtName: "學甲區" },
        { districtId: "727", districtName: "北門區" },
        { districtId: "730", districtName: "新營區" },
        { districtId: "731", districtName: "後壁區" },
        { districtId: "732", districtName: "白河區" },
        { districtId: "733", districtName: "東山區" },
        { districtId: "734", districtName: "六甲區" },
        { districtId: "735", districtName: "下營區" },
        { districtId: "736", districtName: "柳營區" },
        { districtId: "737", districtName: "鹽水區" },
        { districtId: "741", districtName: "善化區" },
        { districtId: "742", districtName: "大內區" },
        { districtId: "743", districtName: "山上區" },
        { districtId: "744", districtName: "新市區" },
        { districtId: "745", districtName: "安定區" },
      ],
    },
    {
      countryId: "64",
      countryName: "高雄市",
      districts: [
        { districtId: "811", districtName: "楠梓區" },
        { districtId: "813", districtName: "左營區" },
        { districtId: "804", districtName: "鼓山區" },
        { districtId: "807", districtName: "三民區" },
        { districtId: "802", districtName: "苓雅區" },
        { districtId: "800", districtName: "新興區" },
        { districtId: "803", districtName: "鹽埕區" },
        { districtId: "801", districtName: "前金區" },
        { districtId: "806", districtName: "前鎮區" },
        { districtId: "805", districtName: "旗津區" },
        { districtId: "812", districtName: "小港區" },
        { districtId: "830", districtName: "鳳山區" },
        { districtId: "851", districtName: "茂林區" },
        { districtId: "847", districtName: "甲仙區" },
        { districtId: "844", districtName: "六龜區" },
        { districtId: "846", districtName: "杉林區" },
        { districtId: "843", districtName: "美濃區" },
        { districtId: "845", districtName: "內門區" },
        { districtId: "814", districtName: "仁武區" },
        { districtId: "823", districtName: "田寮區" },
        { districtId: "842", districtName: "旗山區" },
        { districtId: "826", districtName: "梓官區" },
        { districtId: "822", districtName: "阿蓮區" },
        { districtId: "829", districtName: "湖內區" },
        { districtId: "820", districtName: "岡山區" },
        { districtId: "852", districtName: "茄萣區" },
        { districtId: "821", districtName: "路竹區" },
        { districtId: "833", districtName: "鳥松區" },
        { districtId: "828", districtName: "永安區" },
        { districtId: "824", districtName: "燕巢區" },
        { districtId: "840", districtName: "大樹區" },
        { districtId: "831", districtName: "大寮區" },
        { districtId: "832", districtName: "林園區" },
        { districtId: "827", districtName: "彌陀區" },
        { districtId: "825", districtName: "橋頭區" },
        { districtId: "815", districtName: "大社區" },
        { districtId: "848", districtName: "桃源區" },
        { districtId: "849", districtName: "那瑪夏區" },
      ],
    },
    {
      countryId: "10013",
      countryName: "屏東縣",
      districts: [
        { districtId: "900", districtName: "屏東市" },
        { districtId: "902", districtName: "霧臺鄉" },
        { districtId: "903", districtName: "瑪家鄉" },
        { districtId: "904", districtName: "九如鄉" },
        { districtId: "905", districtName: "里港鄉" },
        { districtId: "906", districtName: "高樹鄉" },
        { districtId: "907", districtName: "鹽埔鄉" },
        { districtId: "908", districtName: "長治鄉" },
        { districtId: "909", districtName: "麟洛鄉" },
        { districtId: "911", districtName: "竹田鄉" },
        { districtId: "912", districtName: "內埔鄉" },
        { districtId: "913", districtName: "萬丹鄉" },
        { districtId: "920", districtName: "潮州鎮" },
        { districtId: "921", districtName: "泰武鄉" },
        { districtId: "922", districtName: "來義鄉" },
        { districtId: "923", districtName: "萬巒鄉" },
        { districtId: "924", districtName: "崁頂鄉" },
        { districtId: "925", districtName: "新埤鄉" },
        { districtId: "926", districtName: "南州鄉" },
        { districtId: "927", districtName: "林邊鄉" },
        { districtId: "928", districtName: "東港鎮" },
        { districtId: "929", districtName: "琉球鄉" },
        { districtId: "931", districtName: "佳冬鄉" },
        { districtId: "932", districtName: "新園鄉" },
        { districtId: "940", districtName: "枋寮鄉" },
        { districtId: "941", districtName: "枋山鄉" },
        { districtId: "942", districtName: "春日鄉" },
        { districtId: "943", districtName: "獅子鄉" },
        { districtId: "944", districtName: "車城鄉" },
        { districtId: "945", districtName: "牡丹鄉" },
        { districtId: "946", districtName: "恆春鎮" },
        { districtId: "947", districtName: "滿州鄉" },
        { districtId: "901", districtName: "三地門鄉" },
      ],
    },
  ],
  // 東部 5 個縣市
  east: [
    {
      countryId: "10014",
      countryName: "台東市",
      districts: [
        { districtId: "950", districtName: "臺東市" },
        { districtId: "951", districtName: "綠島鄉" },
        { districtId: "952", districtName: "蘭嶼鄉" },
        { districtId: "953", districtName: "延平鄉" },
        { districtId: "954", districtName: "卑南鄉" },
        { districtId: "955", districtName: "鹿野鄉" },
        { districtId: "956", districtName: "關山鎮" },
        { districtId: "957", districtName: "海端鄉" },
        { districtId: "958", districtName: "池上鄉" },
        { districtId: "959", districtName: "東河鄉" },
        { districtId: "961", districtName: "成功鎮" },
        { districtId: "962", districtName: "長濱鄉" },
        { districtId: "964", districtName: "金峰鄉" },
        { districtId: "965", districtName: "大武鄉" },
        { districtId: "966", districtName: "達仁鄉" },
        { districtId: "963", districtName: "太麻里鄉" },
      ],
    },
    {
      countryId: "10015",
      countryName: "花蓮縣",
      districts: [
        { districtId: "970", districtName: "花蓮市" },
        { districtId: "971", districtName: "新城鄉" },
        { districtId: "972", districtName: "秀林鄉" },
        { districtId: "973", districtName: "吉安鄉" },
        { districtId: "974", districtName: "壽豐鄉" },
        { districtId: "975", districtName: "鳳林鎮" },
        { districtId: "976", districtName: "光復鄉" },
        { districtId: "977", districtName: "豐濱鄉" },
        { districtId: "978", districtName: "瑞穗鄉" },
        { districtId: "979", districtName: "萬榮鄉" },
        { districtId: "981", districtName: "玉里鎮" },
        { districtId: "982", districtName: "卓溪鄉" },
        { districtId: "983", districtName: "富里鄉" },
      ],
    },
    {
      countryId: "10016",
      countryName: "澎湖縣",
      districts: [
        { districtId: "880", districtName: "馬公市" },
        { districtId: "881", districtName: "西嶼鄉" },
        { districtId: "882", districtName: "望安鄉" },
        { districtId: "883", districtName: "七美鄉" },
        { districtId: "884", districtName: "白沙鄉" },
        { districtId: "885", districtName: "湖西鄉" },
      ],
    },
    {
      countryId: "09020",
      countryName: "金門縣",
      districts: [
        { districtId: "890", districtName: "金沙鎮" },
        { districtId: "891", districtName: "金湖鎮" },
        { districtId: "892", districtName: "金寧鄉" },
        { districtId: "893", districtName: "金城鎮" },
        { districtId: "894", districtName: "烈嶼鄉" },
        { districtId: "896", districtName: "烏坵鄉" },
      ],
    },
    {
      countryId: "09007",
      countryName: "連江縣",
      districts: [
        { districtId: "209", districtName: "南竿鄉" },
        { districtId: "210", districtName: "北竿鄉" },
        { districtId: "211", districtName: "莒光鄉" },
        { districtId: "212", districtName: "東引鄉" },
      ],
    },
  ],
};

export default dropdownCities;
